### ISSUE TITLE
Pause youtube when opening MPV

### ISSUE THREAD

**Issue by pcercuei** [fazekmar/yastm#2]
It would be great to have an option to pause the built-in player of Youtube when the "open with MPV" button is clicked.

**Comment by fazekmar** [comment]
It is a good idea. I will check the possibilities about a common solution but I don't want to add any site specific code.

Anyway I recommend to check the browser build in autoplay functionality: [Allow or block media autoplay in Firefox](https://support.mozilla.org/en-US/kb/block-autoplay)
